name: Scala CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}
      - name: Cache SBT coursier cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-sbt-coursioer-cache-${{ hashFiles('**/*.sbt') }}
      - name: Check
        run: sbt  scalafmtCheckAll headerCheck test:headerCheck it:headerCheck
      - name: Run tests
        run: sbt +test +it:test
      
